In [35]:
#Importing pandas
import pandas as pd

In [36]:
#Importing my dataset
df=pd.read_csv(r'C:\Users\HP\Documents\ML\Library Utilization\library_data.csv')

In [44]:
#Confirming my dataset
df[:2]

Level of Study College Mode of Study     Sex    Location Library Form  \
0           Degree  COANRE     Full-Time    Male         NaN      Digital   
1           Degree  COETEC     Full-Time    Male         NaN     Physical   
2          Diploma  COANRE     Full-Time  Female   On-campus     Physical   
3           Degree   COPAS     Full-Time    Male  Off-campus     Physical   
4           Degree   COPAS     Full-Time    Male  Off-campus      Digital   
..             ...     ...           ...     ...         ...          ...   
399         Degree   COPAS     Full-Time    Male  Off-campus     Physical   
400         Degree   COPAS     Full-Time    Male  Off-campus      Digital   
401         Degree   COPAS     Full-Time    Male  Off-campus      Digital   
402         Degree   COPAS     Full-Time    Male  Off-campus      Digital   
403         Degree   COPAS     Full-Time    Male  Off-campus     Physical   

     Score Level of Awarenes  library utilization  
0        6               Low                    0  
1        6               Low                    0  
2       12          Moderate                    1  
3        6               Low                    0  
4        6               Low                    0  
..     ...               ...                  ...  
399     14              High                    1  
400     18              High                    1  
401     18              High                    0  
402     12          Moderate                    1  
403     12          Moderate                    0  

[404 rows x 9 columns]

In [34]:
#Features for column library form
df['Library Form'].value_counts()

Physical/ Tangible (books, newspapers,journals)    208
Digital/ Online (e-books, e-journals etc)          195
Name: Library Form, dtype: int64

In [9]:
#Features for column level of study
df['Level of Study'].value_counts()

Degree     330
Diploma     66
Masters      6
PhD          2
Name: Level of Study, dtype: int64

In [11]:
#Features for column college
df['College'].value_counts()

COPAS     90
COANRE    83
COETEC    80
COHES     76
COHRED    75
Name: College, dtype: int64

In [12]:
#Features for column mode of study
df['Mode of Study'].value_counts()

Full-Time    348
Part-Time     56
Name: Mode of Study, dtype: int64

In [13]:
#Features for column sex
df['Sex'].value_counts()

Male      224
Female    180
Name: Sex, dtype: int64

In [16]:
#Features for column level of awarenes
df['Level of Awarenes'].value_counts()

Moderate    163
High        129
Low         112
Name: Level of Awarenes, dtype: int64

In [45]:
#Labels to predict  
df['library utilization'].value_counts()

Rarely (1-3 times)                203
Sometimes (4-7 times)             149
Frequently (more than 7 times)     52
Name: library utilization, dtype: int64

In [38]:
#Mapping outside of campus to off-campus and within campus to on-campus 
df['Location']=df.Location.map({'Outside of Campus':'Off-campus','Off-campus':'Off-campus','Within/ in school campus':'On-campus','On-campus':'On-campus'})
df['Location'].value_counts()

Off-campus    260
On-campus     141
Name: Location, dtype: int64

In [39]:
#Mapping
df['Library Form']=df['Library Form'].map({'Digital/ Online (e-books, e-journals etc)':'Digital','Physical/ Tangible (books, newspapers,journals)':'Physical'})
df['Library Form'].value_counts()

Physical    208
Digital     195
Name: Library Form, dtype: int64

In [42]:
#Mapping
df['library utilization']=df['library utilization'].map({'Frequently (more than 7 times)':2,'Rarely (1-3 times)':0,'Sometimes (4-7 times)':1})
df['library utilization'].value_counts()

0    203
1    149
2     52
Name: library utilization, dtype: int64

In [40]:
#Dropping irrelevant column
df.drop(columns=['entry'],inplace=True)

In [41]:
#List of my new columns
list(df.columns)

['Level of Study',
 'College',
 'Mode of Study',
 'Sex',
 'Location',
 'Library Form',
 'Score',
 'Level of Awarenes',
 'library utilization']

In [43]:
#My data for X
features=df[['Level of Study',
 'College',
 'Mode of Study',
 'Sex',
 'Location',
 'Library Form',
 'Score',
 'Level of Awarenes']]
features

Level of Study College Mode of Study     Sex    Location Library Form  \
0           Degree  COANRE     Full-Time    Male         NaN      Digital   
1           Degree  COETEC     Full-Time    Male         NaN     Physical   
2          Diploma  COANRE     Full-Time  Female   On-campus     Physical   
3           Degree   COPAS     Full-Time    Male  Off-campus     Physical   
4           Degree   COPAS     Full-Time    Male  Off-campus      Digital   
..             ...     ...           ...     ...         ...          ...   
399         Degree   COPAS     Full-Time    Male  Off-campus     Physical   
400         Degree   COPAS     Full-Time    Male  Off-campus      Digital   
401         Degree   COPAS     Full-Time    Male  Off-campus      Digital   
402         Degree   COPAS     Full-Time    Male  Off-campus      Digital   
403         Degree   COPAS     Full-Time    Male  Off-campus     Physical   

     Score Level of Awarenes  
0        6               Low  
1        6               Low  
2       12          Moderate  
3        6               Low  
4        6               Low  
..     ...               ...  
399     14              High  
400     18              High  
401     18              High  
402     12          Moderate  
403     12          Moderate  

[404 rows x 8 columns]

In [45]:
#Creating dummy variables for the features
df_dm = pd.get_dummies(features)
print(df_dm.columns)

Index(['Score', 'Level of Study_Degree', 'Level of Study_Diploma',
       'Level of Study_Masters', 'Level of Study_PhD', 'College_COANRE',
       'College_COETEC', 'College_COHES', 'College_COHRED', 'College_COPAS',
       'Mode of Study_Full-Time', 'Mode of Study_Part-Time', 'Sex_Female',
       'Sex_Male', 'Location_Off-campus', 'Location_On-campus',
       'Library Form_Digital', 'Library Form_Physical',
       'Level of Awarenes_High', 'Level of Awarenes_Low',
       'Level of Awarenes_Moderate'],
      dtype='object')


In [46]:
#Confirming the dummy variables dataset
df_dm.head()

Score  Level of Study_Degree  Level of Study_Diploma  \
0      6                      1                       0   
1      6                      1                       0   
2     12                      0                       1   
3      6                      1                       0   
4      6                      1                       0   

   Level of Study_Masters  Level of Study_PhD  College_COANRE  College_COETEC  \
0                       0                   0               1               0   
1                       0                   0               0               1   
2                       0                   0               1               0   
3                       0                   0               0               0   
4                       0                   0               0               0   

   College_COHES  College_COHRED  College_COPAS  ...  Mode of Study_Part-Time  \
0              0               0              0  ...                        0   
1              0               0              0  ...                        0   
2              0               0              0  ...                        0   
3              0               0              1  ...                        0   
4              0               0              1  ...                        0   

   Sex_Female  Sex_Male  Location_Off-campus  Location_On-campus  \
0           0         1                    0                   0   
1           0         1                    0                   0   
2           1         0                    0                   1   
3           0         1                    1                   0   
4           0         1                    1                   0   

   Library Form_Digital  Library Form_Physical  Level of Awarenes_High  \
0                     1                      0                       0   
1                     0                      1                       0   
2                     0                      1                       0   
3                     0                      1                       0   
4                     1                      0                       0   

   Level of Awarenes_Low  Level of Awarenes_Moderate  
0                      1                           0  
1                      1                           0  
2                      0                           1  
3                      1                           0  
4                      1                           0  

[5 rows x 21 columns]

In [47]:
#Importing numpy
#Converting the labels(y) series to an array
import numpy as np
y=np.array(df['library utilization'])
y

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 2, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 2,
       0, 1, 0, 1, 0, 1, 2, 0, 0, 1, 0, 2, 1, 0, 1, 0, 1, 0, 1, 0, 1, 2,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 2, 1, 1, 1, 2, 1, 2, 1, 1, 0, 1, 2, 1, 2, 1, 1,
       2, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 2, 1, 2,
       1, 0, 1, 1, 2, 2, 0, 1, 1, 0, 1, 0, 2, 1, 1, 0, 2, 1, 1, 2, 1, 2,
       0, 2, 0, 0, 0, 2, 2, 1, 1, 1, 2, 0, 0, 1, 1, 0, 2, 0, 1, 1, 2, 2,
       0, 1, 2, 0, 1, 0, 1, 1, 1, 1, 2, 0, 1, 0, 1, 1, 0, 1, 2, 1, 1, 0,
       1, 1, 2, 1, 0, 0, 1, 2, 0, 1, 0, 0, 2, 1, 0, 0, 2, 1, 0, 1, 1, 0,
       0, 1, 0, 2, 0, 1, 1, 2, 0, 0, 1, 0, 2, 1, 0, 1, 2, 0, 1, 1, 0, 2,
       2, 0, 0, 0, 2, 1, 2, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 2, 0, 1, 1, 0, 1,

In [49]:
#the values method converts the dataset to a 2D array
#Shape of X data
X=df_dm.values
X.shape

(404, 21)

In [50]:
#Shape of y
y.shape

(404,)

# LOGISTIC REGRESSION

In [51]:
#Building a logistic regression model
#Importing necessary modules
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
print("Train score: {:.2f}".format(logreg.score(X_train, y_train)))
print("Test score: {:.2f}".format(logreg.score(X_test, y_test)))

Train score: 0.66
Test score: 0.68


C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [52]:
#Fetching the 3rd row of the X array
X_new=np.array([X[2]])
print(X_new.shape)
X_new

(1, 21)


array([[12,  0,  1,  0,  0,  1,  0,  0,  0,  0,  1,  0,  1,  0,  0,  1,
         0,  1,  0,  0,  1]], dtype=int64)

In [53]:
#Predicting the 3rd row
pred=logreg.predict(X_new)
if pred==0:
    print('Rarely')
elif pred==1:
    print('Sometimes')
else:
    print('Frequently')

Sometimes


# GRADIENT BOOSTING MACHINES

In [54]:
#Building a GB machine model
#Importing necessary modules
from sklearn.ensemble import GradientBoostingClassifier

In [55]:
#Creating my GBM model
#By default, 100 trees of maximum depth 3 and a learning rate of 0.1 are used
gbrt = GradientBoostingClassifier(random_state=0)
gbrt.fit(X_train, y_train)

GradientBoostingClassifier(random_state=0)

In [56]:
#Accuracy score
print("Accuracy on training set: {:.3f}".format(gbrt.score(X_train, y_train)))
print("Accuracy on test set: {:.3f}".format(gbrt.score(X_test, y_test)))


Accuracy on training set: 0.832
Accuracy on test set: 0.703


In [61]:
#Fetching the 16th row of the array
X_newest=np.array([X[15]])
print(X_newest.shape)
X_newest

(1, 21)


array([[14,  1,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  1,  0,  1,  0,
         0,  1,  1,  0,  0]], dtype=int64)

In [59]:
#Predicting the 16th row
predic=gbrt.predict(X_newest)
predic

#Wrong prediction!
#Model wasn't suffucient

array([0], dtype=int64)

# DECISION TREES

In [27]:
#Building a decision tree model
#Importing necessary modules
from sklearn.tree import DecisionTreeClassifier

In [28]:
#The model
tree = DecisionTreeClassifier(random_state=0)
tree.fit(X_train, y_train)
print("Accuracy on training set: {:.3f}".format(tree.score(X_train, y_train)))
print("Accuracy on test set: {:.3f}".format(tree.score(X_test, y_test)))


Accuracy on training set: 0.908
Accuracy on test set: 0.644


In [29]:
#Lets try pre-prunning now to reduce overfitting
#Lets set max_depth=4, meaning only four consecutive questions can be asked
treeprun = DecisionTreeClassifier(max_depth=4, random_state=0)
treeprun.fit(X_train, y_train)
print("Accuracy on training set: {:.3f}".format(treeprun.score(X_train, y_train)))
print("Accuracy on test set: {:.3f}".format(treeprun.score(X_test, y_test)))

Accuracy on training set: 0.723
Accuracy on test set: 0.683


# RANDOM FOREST

In [31]:
#Building a random forest model
#Importing necessary modules
from sklearn.ensemble import RandomForestClassifier

In [32]:
#Applying a forest of 100 trees
forest = RandomForestClassifier(n_estimators=100, random_state=0)
forest.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [33]:
#Accuracy score
print("Accuracy on training set: {:.3f}".format(forest.score(X_train, y_train)))
print("Accuracy on test set: {:.3f}".format(forest.score(X_test, y_test)))

#The models are not suffucient probably due to the features collected during the survey being insignificant

Accuracy on training set: 0.908
Accuracy on test set: 0.703
